# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Denis Šaško
email: denissasko@gmail.com
description: "Frontend developer from Zagreb, Croatia"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dsasko.github.io" # the base hostname & protocol for your site

# Analytics code
google_tag_manager_id: GTM-MCC2FB3

# Domain name
domain: dsasko.github.io

# Social media
github_username: dsasko
linkedin_username: dsasko

# Build settings
markdown: kramdown

# SASS Options
sass:
  style: compressed

# Versioning
version_id: 20210112
