services:
  jekyll:
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle/:/usr/local/bundle
    ports:
      - "4000:4000"
    command: bash -c "
        ruby --version
        && bundle --version
        && gem install bundler jekyll
        && bundle add webrick
        && jekyll serve --force_polling --drafts
      "